services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: farmer_crm
      POSTGRES_USER: postgres  # Стандартный пользователь (как принято)
      # POSTGRES_PASSWORD не указываем для локальной разработки
    ports:
      - "5433:5432"  # Используем 5433 чтобы не конфликтовать с локальным PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - farmer_network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      # В Docker тоже используем стандартного postgres пользователя
      - DATABASE_URL=postgresql://postgres@postgres:5432/farmer_crm
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    networks:
      - farmer_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  bot:
    build: ./bot
    environment:
      # В Docker тоже используем стандартного postgres пользователя
      - DATABASE_URL=postgresql://postgres@postgres:5432/farmer_crm
      - BACKEND_URL=http://backend:8000
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - ./bot:/app
    networks:
      - farmer_network
    command: python main.py

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:8000
      - VITE_API_BASE_URL=http://backend:8000/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - farmer_network
    command: npm run dev

  # Добавляем nginx для продакшена (опционально)
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - farmer_network
    profiles:
      - production  # Запускается только с профилем production

volumes:
  postgres_data:

networks:
  farmer_network:
    driver: bridge