"""Make pact_contact_id nullable

Revision ID: 7a272ed4d88a
Revises: bd01e91491f8
Create Date: 2025-08-06 13:08:43.123446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a272ed4d88a'
down_revision: Union[str, None] = 'bd01e91491f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'pact_contact_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'pact_contact_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###